// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               unknown
// source: epoch/tx.proto

/* eslint-disable */

export const protobufPackage = "seiprotocol.seichain.epoch";
