import { ColorSchemeScript } from "@mantine/core";
import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Providers } from "@/components/providers";

import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";

export const metadata: Metadata = {
	title: "Sei Next App (Wagmi)",
	description: "Generated by create sei app",
	icons: {
		icon: "/brand/sei-mark.png",
		apple: "/brand/sei-mark.png",
	},
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
	return (
		<html lang="en" data-mantine-color-scheme="light">
			<head>
				<title>Sei Next App (Wagmi)</title>
				<ColorSchemeScript defaultColorScheme="light" />
			</head>
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
