// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: confidentialtransfers/cryptography.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Ciphertext represents the ciphertext of a message.
type Ciphertext struct {
	// Pedersen commitment bytes.
	C []byte `protobuf:"bytes,1,opt,name=c,proto3" json:"c,omitempty"`
	// Decryption handle bytes.
	D                    []byte   `protobuf:"bytes,2,opt,name=d,proto3" json:"d,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ciphertext) Reset()         { *m = Ciphertext{} }
func (m *Ciphertext) String() string { return proto.CompactTextString(m) }
func (*Ciphertext) ProtoMessage()    {}
func (*Ciphertext) Descriptor() ([]byte, []int) {
	return fileDescriptor_3793c57433c8e5f9, []int{0}
}
func (m *Ciphertext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ciphertext.Unmarshal(m, b)
}
func (m *Ciphertext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ciphertext.Marshal(b, m, deterministic)
}
func (m *Ciphertext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ciphertext.Merge(m, src)
}
func (m *Ciphertext) XXX_Size() int {
	return xxx_messageInfo_Ciphertext.Size(m)
}
func (m *Ciphertext) XXX_DiscardUnknown() {
	xxx_messageInfo_Ciphertext.DiscardUnknown(m)
}

var xxx_messageInfo_Ciphertext proto.InternalMessageInfo

func (m *Ciphertext) GetC() []byte {
	if m != nil {
		return m.C
	}
	return nil
}

func (m *Ciphertext) GetD() []byte {
	if m != nil {
		return m.D
	}
	return nil
}

func init() {
	proto.RegisterType((*Ciphertext)(nil), "seiprotocol.seichain.confidentialtransfers.Ciphertext")
}

func init() {
	proto.RegisterFile("confidentialtransfers/cryptography.proto", fileDescriptor_3793c57433c8e5f9)
}

var fileDescriptor_3793c57433c8e5f9 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8e, 0xb1, 0xca, 0xc2, 0x30,
	0x14, 0x46, 0xc9, 0x3f, 0xfc, 0x43, 0xe8, 0xd4, 0xa9, 0xa3, 0x38, 0x15, 0xc1, 0x64, 0xf0, 0x01,
	0x44, 0x7d, 0x03, 0x47, 0xb7, 0xf4, 0xf6, 0xb6, 0xb9, 0x50, 0x93, 0x90, 0x7b, 0x85, 0xe6, 0xed,
	0xc5, 0x88, 0x5b, 0xb7, 0xef, 0x0c, 0x87, 0xf3, 0xe9, 0x1e, 0x62, 0x98, 0x68, 0xc4, 0x20, 0xe4,
	0x16, 0xc9, 0x2e, 0xf0, 0x84, 0x99, 0x2d, 0xe4, 0x92, 0x24, 0xce, 0xd9, 0x25, 0x5f, 0x4c, 0xca,
	0x51, 0x62, 0x7b, 0x60, 0xa4, 0xba, 0x20, 0x2e, 0x86, 0x91, 0xc0, 0x3b, 0x0a, 0x66, 0x53, 0xdf,
	0xf7, 0x5a, 0xdf, 0x28, 0x79, 0xcc, 0x82, 0xab, 0xb4, 0x8d, 0x56, 0xd0, 0xa9, 0x9d, 0xea, 0x9b,
	0xbb, 0x82, 0x0f, 0x8d, 0xdd, 0xdf, 0x97, 0xc6, 0xeb, 0xe5, 0x71, 0x9e, 0x49, 0xfc, 0x6b, 0x30,
	0x10, 0x9f, 0x96, 0x91, 0x8e, 0xbf, 0x46, 0x85, 0x1a, 0xb1, 0xab, 0xdd, 0x7e, 0x29, 0x25, 0x21,
	0x0f, 0xff, 0xd5, 0x38, 0xbd, 0x03, 0x00, 0x00, 0xff, 0xff, 0x27, 0xd5, 0x4a, 0x58, 0xcb, 0x00,
	0x00, 0x00,
}
