name: Checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch the full history instead of a shallow clone

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.x"

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint & Format Check
        run: bun run check

      - name: Build All Packages
        run: bun run build

      - name: Test
        run: bun test packages/*
