name: Run & Upload Test Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - feature/**

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch the full history instead of a shallow clone

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.x"

      - uses: browser-actions/setup-chrome@v1
      - run: chrome --version

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build packages
        run: bun run build

      - name: Run tests with coverage
        run: bun test --coverage --coverage-reporter=lcov packages/*

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: '**/lcov.info'
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
