name: UCI
run-name: UCI / Stale Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  stale:
    name: Stale
    permissions:
      issues: write
      pull-requests: write
    # See: https://github.com/sei-protocol/uci/releases/tag/v0.0.15
    uses: sei-protocol/uci/.github/workflows/stale-check.yml@65901242783550521f25a19199a6b10e54550b97
    with:
      days-before-pr-stale: 28
